trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  client_id: $(client_id)  # Reference to the variable created in Azure DevOps
  client_secret: $(client_secret)
  tenant_id: $(tenant_id)
  subscription_id: $(subscription_id)
  terraform_version: '1.3.0'  # Set the Terraform version you need

steps:
- task: UseTerraform@0
  inputs:
    version: $(terraform_version)

- task: TerraformInstaller@0
  inputs:
    terraformVersion: $(terraform_version)

- script: |
    echo "Initializing Terraform..."
    terraform init
  displayName: 'Terraform Init'

- script: |
    echo "Applying Terraform configuration..."
    terraform apply -auto-approve
  displayName: 'Terraform Apply'

- task: TerraformOutput@0
  displayName: 'Terraform Output'
