trigger:
  branches:
    include:
      - main

pool:
  name: Default
  vmImage: 'windows-latest'

steps:
   - script: |
      # Initialize Packer project and install required plugins
      packer init windows-vm.pkr.hcl
    displayName: 'Initialize Packer Project'

  - script: |
      # Build virtual machine image with Packer using WinRM 
      packer build windows-vm.pkr.hcl
    displayName: 'Build Virtual Machine Image'
